// Generated by d2w fhir generate - do not edit

CodeSystem: D2DE_CS
Id: d2-de-cs
Title: "DHIS2 data elements"
Description: "DHIS2 data elements captured by the generated questionnaires. Concept codes are DHIS2 data element UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2DE_VS)
* ^property[+].code = #dhis2-code
* ^property[=].uri = "http://dhis2.org/fhir/property/dhis2-code"
* ^property[=].description = "DHIS2 data element code."
* ^property[=].type = #string
* ^property[+].code = #domain
* ^property[=].uri = "http://dhis2.org/fhir/property/domain"
* ^property[=].description = "DHIS2 data element domain type."
* ^property[=].type = #code
* ^property[+].code = #form-name
* ^property[=].uri = "http://dhis2.org/fhir/property/form-name"
* ^property[=].description = "DHIS2 data element form name, which is the text of every question asking it. Absent where DHIS2 states none, in which case the question is asked under the concept display."
* ^property[=].type = #string
* ^property[+].code = #value-type
* ^property[=].uri = "http://dhis2.org/fhir/property/value-type"
* ^property[=].description = "DHIS2 data element value type."
* ^property[=].type = #code
* #uf3svrmp8Oj "Birth certificate"
* #uf3svrmp8Oj ^property[+].code = #dhis2-code
* #uf3svrmp8Oj ^property[=].valueString = "DE_424405"
* #uf3svrmp8Oj ^property[+].code = #domain
* #uf3svrmp8Oj ^property[=].valueCode = #tracker
* #uf3svrmp8Oj ^property[+].code = #value-type
* #uf3svrmp8Oj ^property[=].valueCode = #FILE_RESOURCE
* #wQLfBvPrXqq "MCH ARV at birth"
* #wQLfBvPrXqq ^property[+].code = #dhis2-code
* #wQLfBvPrXqq ^property[=].valueString = "DE_2008294"
* #wQLfBvPrXqq ^property[+].code = #domain
* #wQLfBvPrXqq ^property[=].valueCode = #tracker
* #wQLfBvPrXqq ^property[+].code = #form-name
* #wQLfBvPrXqq ^property[=].valueString = "ARV at birth"
* #wQLfBvPrXqq ^property[+].code = #value-type
* #wQLfBvPrXqq ^property[=].valueCode = #TEXT
* #a3kGcGDCuk6 "MCH Apgar Score"
* #a3kGcGDCuk6 ^property[+].code = #dhis2-code
* #a3kGcGDCuk6 ^property[=].valueString = "DE_2006098"
* #a3kGcGDCuk6 ^property[+].code = #domain
* #a3kGcGDCuk6 ^property[=].valueCode = #tracker
* #a3kGcGDCuk6 ^property[+].code = #form-name
* #a3kGcGDCuk6 ^property[=].valueString = "Apgar Score"
* #a3kGcGDCuk6 ^property[+].code = #value-type
* #a3kGcGDCuk6 ^property[=].valueCode = #NUMBER
* #H6uSAMO5WLD "MCH Apgar comment"
* #H6uSAMO5WLD ^property[+].code = #dhis2-code
* #H6uSAMO5WLD ^property[=].valueString = "DE_391382"
* #H6uSAMO5WLD ^property[+].code = #domain
* #H6uSAMO5WLD ^property[=].valueCode = #tracker
* #H6uSAMO5WLD ^property[+].code = #form-name
* #H6uSAMO5WLD ^property[=].valueString = "Apgar comment"
* #H6uSAMO5WLD ^property[+].code = #value-type
* #H6uSAMO5WLD ^property[=].valueCode = #LONG_TEXT
* #bx6fsa0t90x "MCH BCG dose"
* #bx6fsa0t90x ^property[+].code = #dhis2-code
* #bx6fsa0t90x ^property[=].valueString = "DE_2006101"
* #bx6fsa0t90x ^property[+].code = #domain
* #bx6fsa0t90x ^property[=].valueCode = #tracker
* #bx6fsa0t90x ^property[+].code = #form-name
* #bx6fsa0t90x ^property[=].valueString = "BCG dose"
* #bx6fsa0t90x ^property[+].code = #value-type
* #bx6fsa0t90x ^property[=].valueCode = #BOOLEAN
* #sj3j9Hwc7so "MCH Child ARVs"
* #sj3j9Hwc7so ^property[+].code = #dhis2-code
* #sj3j9Hwc7so ^property[=].valueString = "DE_2006100"
* #sj3j9Hwc7so ^property[+].code = #domain
* #sj3j9Hwc7so ^property[=].valueCode = #tracker
* #sj3j9Hwc7so ^property[+].code = #form-name
* #sj3j9Hwc7so ^property[=].valueString = "Child ARVs"
* #sj3j9Hwc7so ^property[+].code = #value-type
* #sj3j9Hwc7so ^property[=].valueCode = #TEXT
* #pOe0ogW4OWd "MCH DPT dose"
* #pOe0ogW4OWd ^property[+].code = #dhis2-code
* #pOe0ogW4OWd ^property[=].valueString = "DE_2006105"
* #pOe0ogW4OWd ^property[+].code = #domain
* #pOe0ogW4OWd ^property[=].valueCode = #tracker
* #pOe0ogW4OWd ^property[+].code = #form-name
* #pOe0ogW4OWd ^property[=].valueString = "DPT dose"
* #pOe0ogW4OWd ^property[+].code = #value-type
* #pOe0ogW4OWd ^property[=].valueCode = #TEXT
* #hDZbpskhqDd "MCH HIV Test Type"
* #hDZbpskhqDd ^property[+].code = #dhis2-code
* #hDZbpskhqDd ^property[=].valueString = "DE_2006108"
* #hDZbpskhqDd ^property[+].code = #domain
* #hDZbpskhqDd ^property[=].valueCode = #tracker
* #hDZbpskhqDd ^property[+].code = #form-name
* #hDZbpskhqDd ^property[=].valueString = "HIV Test Type"
* #hDZbpskhqDd ^property[+].code = #value-type
* #hDZbpskhqDd ^property[=].valueCode = #TEXT
* #lNNb3truQoi "MCH IPT dose"
* #lNNb3truQoi ^property[+].code = #dhis2-code
* #lNNb3truQoi ^property[=].valueString = "DE_2005744"
* #lNNb3truQoi ^property[+].code = #domain
* #lNNb3truQoi ^property[=].valueCode = #tracker
* #lNNb3truQoi ^property[+].code = #form-name
* #lNNb3truQoi ^property[=].valueString = "IPT dose"
* #lNNb3truQoi ^property[+].code = #value-type
* #lNNb3truQoi ^property[=].valueCode = #TEXT
* #X8zyunlgUfM "MCH Infant Feeding"
* #X8zyunlgUfM ^property[+].code = #dhis2-code
* #X8zyunlgUfM ^property[=].valueString = "DE_2006103"
* #X8zyunlgUfM ^property[+].code = #domain
* #X8zyunlgUfM ^property[=].valueCode = #tracker
* #X8zyunlgUfM ^property[+].code = #form-name
* #X8zyunlgUfM ^property[=].valueString = "Infant Feeding"
* #X8zyunlgUfM ^property[+].code = #value-type
* #X8zyunlgUfM ^property[=].valueCode = #TEXT
* #cYGaxwK615G "MCH Infant HIV Test Result"
* #cYGaxwK615G ^property[+].code = #dhis2-code
* #cYGaxwK615G ^property[=].valueString = "DE_2006107"
* #cYGaxwK615G ^property[+].code = #domain
* #cYGaxwK615G ^property[=].valueCode = #tracker
* #cYGaxwK615G ^property[+].code = #form-name
* #cYGaxwK615G ^property[=].valueString = "Infant HIV Test Result"
* #cYGaxwK615G ^property[+].code = #value-type
* #cYGaxwK615G ^property[=].valueCode = #TEXT
* #GQY2lXrypjO "MCH Infant Weight (g)"
* #GQY2lXrypjO ^property[+].code = #dhis2-code
* #GQY2lXrypjO ^property[=].valueString = "DE_2006099"
* #GQY2lXrypjO ^property[+].code = #domain
* #GQY2lXrypjO ^property[=].valueCode = #tracker
* #GQY2lXrypjO ^property[+].code = #form-name
* #GQY2lXrypjO ^property[=].valueString = "Infant Weight (g)"
* #GQY2lXrypjO ^property[+].code = #value-type
* #GQY2lXrypjO ^property[=].valueCode = #NUMBER
* #FqlgKAG8HOu "MCH Measles dose"
* #FqlgKAG8HOu ^property[+].code = #dhis2-code
* #FqlgKAG8HOu ^property[=].valueString = "DE_2006125"
* #FqlgKAG8HOu ^property[+].code = #domain
* #FqlgKAG8HOu ^property[=].valueCode = #tracker
* #FqlgKAG8HOu ^property[+].code = #form-name
* #FqlgKAG8HOu ^property[=].valueString = "Measles dose"
* #FqlgKAG8HOu ^property[+].code = #value-type
* #FqlgKAG8HOu ^property[=].valueCode = #BOOLEAN
* #ebaJjqltK5N "MCH OPV dose"
* #ebaJjqltK5N ^property[+].code = #dhis2-code
* #ebaJjqltK5N ^property[=].valueString = "DE_2006104"
* #ebaJjqltK5N ^property[+].code = #domain
* #ebaJjqltK5N ^property[=].valueCode = #tracker
* #ebaJjqltK5N ^property[+].code = #form-name
* #ebaJjqltK5N ^property[=].valueString = "OPV dose"
* #ebaJjqltK5N ^property[+].code = #value-type
* #ebaJjqltK5N ^property[=].valueCode = #TEXT
* #vTUhAUZFoys "MCH Penta dose"
* #vTUhAUZFoys ^property[+].code = #dhis2-code
* #vTUhAUZFoys ^property[=].valueString = "DE_347311"
* #vTUhAUZFoys ^property[+].code = #domain
* #vTUhAUZFoys ^property[=].valueCode = #tracker
* #vTUhAUZFoys ^property[+].code = #form-name
* #vTUhAUZFoys ^property[=].valueString = "Penta dose"
* #vTUhAUZFoys ^property[+].code = #value-type
* #vTUhAUZFoys ^property[=].valueCode = #TEXT
* #BeynU4L6VCQ "MCH Results given to caretaker"
* #BeynU4L6VCQ ^property[+].code = #dhis2-code
* #BeynU4L6VCQ ^property[=].valueString = "DE_2006110"
* #BeynU4L6VCQ ^property[+].code = #domain
* #BeynU4L6VCQ ^property[=].valueCode = #tracker
* #BeynU4L6VCQ ^property[+].code = #form-name
* #BeynU4L6VCQ ^property[=].valueString = "Results given to caretaker"
* #BeynU4L6VCQ ^property[+].code = #value-type
* #BeynU4L6VCQ ^property[=].valueCode = #TEXT
* #aei1xRjSU2l "MCH Septrin Given"
* #aei1xRjSU2l ^property[+].code = #dhis2-code
* #aei1xRjSU2l ^property[=].valueString = "DE_2006109"
* #aei1xRjSU2l ^property[+].code = #domain
* #aei1xRjSU2l ^property[=].valueCode = #tracker
* #aei1xRjSU2l ^property[+].code = #form-name
* #aei1xRjSU2l ^property[=].valueString = "Septrin Given"
* #aei1xRjSU2l ^property[+].code = #value-type
* #aei1xRjSU2l ^property[=].valueCode = #TEXT
* #OuJ6sgPyAbC "MCH Visit Comment"
* #OuJ6sgPyAbC ^property[+].code = #dhis2-code
* #OuJ6sgPyAbC ^property[=].valueString = "DE_2008126"
* #OuJ6sgPyAbC ^property[+].code = #domain
* #OuJ6sgPyAbC ^property[=].valueCode = #tracker
* #OuJ6sgPyAbC ^property[+].code = #form-name
* #OuJ6sgPyAbC ^property[=].valueString = "Visit comment (optional)"
* #OuJ6sgPyAbC ^property[+].code = #value-type
* #OuJ6sgPyAbC ^property[=].valueCode = #LONG_TEXT
* #HLmTEmupdX0 "MCH Vit A"
* #HLmTEmupdX0 ^property[+].code = #dhis2-code
* #HLmTEmupdX0 ^property[=].valueString = "DE_2006106"
* #HLmTEmupdX0 ^property[+].code = #domain
* #HLmTEmupdX0 ^property[=].valueCode = #tracker
* #HLmTEmupdX0 ^property[+].code = #form-name
* #HLmTEmupdX0 ^property[=].valueString = "Vit A"
* #HLmTEmupdX0 ^property[+].code = #value-type
* #HLmTEmupdX0 ^property[=].valueCode = #BOOLEAN
* #UXz7xuGCEhU "MCH Weight (g)"
* #UXz7xuGCEhU ^property[+].code = #dhis2-code
* #UXz7xuGCEhU ^property[=].valueString = "DE_2005736"
* #UXz7xuGCEhU ^property[+].code = #domain
* #UXz7xuGCEhU ^property[=].valueCode = #tracker
* #UXz7xuGCEhU ^property[+].code = #form-name
* #UXz7xuGCEhU ^property[=].valueString = "Weight (g)"
* #UXz7xuGCEhU ^property[+].code = #value-type
* #UXz7xuGCEhU ^property[=].valueCode = #NUMBER
* #rxBfISxXS2U "MCH Yellow fever dose"
* #rxBfISxXS2U ^property[+].code = #dhis2-code
* #rxBfISxXS2U ^property[=].valueString = "DE_2006126"
* #rxBfISxXS2U ^property[+].code = #domain
* #rxBfISxXS2U ^property[=].valueCode = #tracker
* #rxBfISxXS2U ^property[+].code = #form-name
* #rxBfISxXS2U ^property[=].valueString = "Yellow fever dose"
* #rxBfISxXS2U ^property[+].code = #value-type
* #rxBfISxXS2U ^property[=].valueCode = #BOOLEAN
* #cZnQDuF3IDz "Stock PHU discarded BCG"
* #cZnQDuF3IDz ^property[+].code = #dhis2-code
* #cZnQDuF3IDz ^property[=].valueString = "DE_360103"
* #cZnQDuF3IDz ^property[+].code = #domain
* #cZnQDuF3IDz ^property[=].valueCode = #aggregate
* #cZnQDuF3IDz ^property[+].code = #value-type
* #cZnQDuF3IDz ^property[=].valueCode = #NUMBER
* #cZnQDuF3IDz ^designation[+].language = #en-GB
* #cZnQDuF3IDz ^designation[=].value = "Stock PHU discarded BCG (doses, NOT vials)"
* #FvKdfA2SuWI "Stock PHU discarded Measles"
* #FvKdfA2SuWI ^property[+].code = #dhis2-code
* #FvKdfA2SuWI ^property[=].valueString = "DE_360126"
* #FvKdfA2SuWI ^property[+].code = #domain
* #FvKdfA2SuWI ^property[=].valueCode = #aggregate
* #FvKdfA2SuWI ^property[+].code = #value-type
* #FvKdfA2SuWI ^property[=].valueCode = #NUMBER
* #FvKdfA2SuWI ^designation[+].language = #en-GB
* #FvKdfA2SuWI ^designation[=].value = "Stock PHU discarded MEASLES (doses, NOT vials)"
* #WVrH6j3Wfye "Stock PHU discarded OPV"
* #WVrH6j3Wfye ^property[+].code = #dhis2-code
* #WVrH6j3Wfye ^property[=].valueString = "DE_360129"
* #WVrH6j3Wfye ^property[+].code = #domain
* #WVrH6j3Wfye ^property[=].valueCode = #aggregate
* #WVrH6j3Wfye ^property[+].code = #value-type
* #WVrH6j3Wfye ^property[=].valueCode = #NUMBER
* #WVrH6j3Wfye ^designation[+].language = #en-GB
* #WVrH6j3Wfye ^designation[=].value = "Stock PHU discarded OPV (doses, NOT vials)"
* #p1MDHOT6ENy "Stock PHU dispensed BCG"
* #p1MDHOT6ENy ^property[+].code = #dhis2-code
* #p1MDHOT6ENy ^property[=].valueString = "DE_360049"
* #p1MDHOT6ENy ^property[+].code = #domain
* #p1MDHOT6ENy ^property[=].valueCode = #aggregate
* #p1MDHOT6ENy ^property[+].code = #value-type
* #p1MDHOT6ENy ^property[=].valueCode = #NUMBER
* #p1MDHOT6ENy ^designation[+].language = #en-GB
* #p1MDHOT6ENy ^designation[=].value = "Stock PHU dispensed BCG (doses, NOT vials)"
* #lVknokmR4Ip "Stock PHU dispensed Measles"
* #lVknokmR4Ip ^property[+].code = #dhis2-code
* #lVknokmR4Ip ^property[=].valueString = "DE_360072"
* #lVknokmR4Ip ^property[+].code = #domain
* #lVknokmR4Ip ^property[=].valueCode = #aggregate
* #lVknokmR4Ip ^property[+].code = #value-type
* #lVknokmR4Ip ^property[=].valueCode = #NUMBER
* #lVknokmR4Ip ^designation[+].language = #en-GB
* #lVknokmR4Ip ^designation[=].value = "Stock PHU dispensed MEASLES (doses, NOT vials)"
* #FTINmL2lehN "Stock PHU dispensed OPV"
* #FTINmL2lehN ^property[+].code = #dhis2-code
* #FTINmL2lehN ^property[=].valueString = "DE_360075"
* #FTINmL2lehN ^property[+].code = #domain
* #FTINmL2lehN ^property[=].valueCode = #aggregate
* #FTINmL2lehN ^property[+].code = #value-type
* #FTINmL2lehN ^property[=].valueCode = #NUMBER
* #FTINmL2lehN ^designation[+].language = #en-GB
* #FTINmL2lehN ^designation[=].value = "Stock PHU dispensed OPV (doses, NOT vials)"
* #axVhq1itoQD "Stock PHU received BCG"
* #axVhq1itoQD ^property[+].code = #dhis2-code
* #axVhq1itoQD ^property[=].valueString = "DE_359995"
* #axVhq1itoQD ^property[+].code = #domain
* #axVhq1itoQD ^property[=].valueCode = #aggregate
* #axVhq1itoQD ^property[+].code = #value-type
* #axVhq1itoQD ^property[=].valueCode = #NUMBER
* #axVhq1itoQD ^designation[+].language = #en-GB
* #axVhq1itoQD ^designation[=].value = "Stock PHU received BCG (doses, NOT vials)"
* #XNrjXqZrHD8 "Stock PHU received Measles"
* #XNrjXqZrHD8 ^property[+].code = #dhis2-code
* #XNrjXqZrHD8 ^property[=].valueString = "DE_360018"
* #XNrjXqZrHD8 ^property[+].code = #domain
* #XNrjXqZrHD8 ^property[=].valueCode = #aggregate
* #XNrjXqZrHD8 ^property[+].code = #value-type
* #XNrjXqZrHD8 ^property[=].valueCode = #NUMBER
* #XNrjXqZrHD8 ^designation[+].language = #en-GB
* #XNrjXqZrHD8 ^designation[=].value = "Stock PHU received MEASLES (doses, NOT vials)"
* #nGCLjZDn0Q4 "Stock PHU received OPV"
* #nGCLjZDn0Q4 ^property[+].code = #dhis2-code
* #nGCLjZDn0Q4 ^property[=].valueString = "DE_360021"
* #nGCLjZDn0Q4 ^property[+].code = #domain
* #nGCLjZDn0Q4 ^property[=].valueCode = #aggregate
* #nGCLjZDn0Q4 ^property[+].code = #value-type
* #nGCLjZDn0Q4 ^property[=].valueCode = #NUMBER
* #nGCLjZDn0Q4 ^designation[+].language = #en-GB
* #nGCLjZDn0Q4 ^designation[=].value = "Stock PHU received OPV (doses, NOT vials)"
* #t99PL3gUxIl "Stock PHU start balance BCG"
* #t99PL3gUxIl ^property[+].code = #dhis2-code
* #t99PL3gUxIl ^property[=].valueString = "DE_359941"
* #t99PL3gUxIl ^property[+].code = #domain
* #t99PL3gUxIl ^property[=].valueCode = #aggregate
* #t99PL3gUxIl ^property[+].code = #value-type
* #t99PL3gUxIl ^property[=].valueCode = #NUMBER
* #t99PL3gUxIl ^designation[+].language = #en-GB
* #t99PL3gUxIl ^designation[=].value = "Stock PHU start balance BCG (doses, NOT vials)"
* #vEAo4KwsAzl "Stock PHU start balance Measles"
* #vEAo4KwsAzl ^property[+].code = #dhis2-code
* #vEAo4KwsAzl ^property[=].valueString = "DE_359964"
* #vEAo4KwsAzl ^property[+].code = #domain
* #vEAo4KwsAzl ^property[=].valueCode = #aggregate
* #vEAo4KwsAzl ^property[+].code = #value-type
* #vEAo4KwsAzl ^property[=].valueCode = #NUMBER
* #vEAo4KwsAzl ^designation[+].language = #en-GB
* #vEAo4KwsAzl ^designation[=].value = "Stock PHU start balance MEASLES (doses, NOT vials)"
* #iuSIObmKutb "Stock PHU start balance OPV"
* #iuSIObmKutb ^property[+].code = #dhis2-code
* #iuSIObmKutb ^property[=].valueString = "DE_359967"
* #iuSIObmKutb ^property[+].code = #domain
* #iuSIObmKutb ^property[=].valueCode = #aggregate
* #iuSIObmKutb ^property[+].code = #value-type
* #iuSIObmKutb ^property[=].valueCode = #NUMBER
* #iuSIObmKutb ^designation[+].language = #en-GB
* #iuSIObmKutb ^designation[=].value = "Stock PHU start balance OPV (doses, NOT vials)"
* #vANAXwtLwcT "WHOMCH Hemoglobin value"
* #vANAXwtLwcT ^property[+].code = #dhis2-code
* #vANAXwtLwcT ^property[=].valueString = "LAB_HB"
* #vANAXwtLwcT ^property[+].code = #domain
* #vANAXwtLwcT ^property[=].valueCode = #tracker
* #vANAXwtLwcT ^property[+].code = #value-type
* #vANAXwtLwcT ^property[=].valueCode = #NUMBER
* #sWoqcoByYmD "WHOMCH Smoking"
* #sWoqcoByYmD ^property[+].code = #dhis2-code
* #sWoqcoByYmD ^property[=].valueString = "STA_SMO"
* #sWoqcoByYmD ^property[+].code = #domain
* #sWoqcoByYmD ^property[=].valueCode = #tracker
* #sWoqcoByYmD ^property[+].code = #value-type
* #sWoqcoByYmD ^property[=].valueCode = #BOOLEAN
* #Ok9OQpitjQr "WHOMCH Smoking cessation counselling provided"
* #Ok9OQpitjQr ^property[+].code = #dhis2-code
* #Ok9OQpitjQr ^property[=].valueString = "EA5_TRE_SMO"
* #Ok9OQpitjQr ^property[+].code = #domain
* #Ok9OQpitjQr ^property[=].valueCode = #tracker
* #Ok9OQpitjQr ^property[+].code = #value-type
* #Ok9OQpitjQr ^property[=].valueCode = #BOOLEAN

ValueSet: D2DE_VS
Id: d2-de-vs
Title: "DHIS2 data elements"
Description: "DHIS2 data elements captured by the generated questionnaires. Concept codes are DHIS2 data element UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2DE_CS
