// Generated by d2w fhir generate - do not edit

Instance: D2OrganizationExample
InstanceOf: D2Organization
Title: "Example DHIS2 Organization"
Description: "A worked D2Organization: Example organisation unit as the legal entity, carrying both DHIS2 identifier slices the profile requires and its hierarchy level. Its identifier value d2-example belongs to no organisation unit, so this example never answers a search for a published one."
Usage: #example
* id = "d2-organization-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "d2-example"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "d2-example"
* active = true
* name = "Example organisation unit"
* type = D2OU_Level_CS#level-2 "District"

Instance: D2LocationExample
InstanceOf: D2Location
Title: "Example DHIS2 Location"
Description: "A worked D2Location: Example organisation unit as the physical place, managed by the D2Organization of the same example. Its identifier value d2-example belongs to no organisation unit, so this example never answers a search for a published one."
Usage: #example
* id = "d2-location-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "d2-example"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "d2-example"
* status = #active
* name = "Example organisation unit"
* description = "A worked D2Location: Example organisation unit as the physical place, managed by the D2Organization of the same example. Its identifier value d2-example belongs to no organisation unit, so this example never answers a search for a published one."
* position.longitude = -11.567171
* position.latitude = 7.295009
* extension[level].valueCoding = D2OU_Level_CS#level-2 "District"
* managingOrganization = Reference(D2OrganizationExample)
