// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-VBqh0ynB2wv-example-1
InstanceOf: D2EventResponse
Title: "Example response - Malaria case registration"
Description: "Example QuestionnaireResponse against the DHIS2 event program Malaria case registration (VBqh0ynB2wv)."
Usage: #example
* id = "VBqh0ynB2wv-example-1"
* extension[D2FormType].valueCode = #event
* questionnaire = "http://example.org/fhir/examples/patient-summary/Questionnaire/VBqh0ynB2wv"
* status = #completed
* subject = Reference(Location/ADeZNq1pKsu)
* authored = "2026-09-12T14:00:00Z"
* item[+].linkId = "qrur9Dvnyt5"
* item[=].answer[+].valueInteger = 905
* item[+].linkId = "oZg33kd9taw"
* item[=].answer[+].valueCoding = D2OS_pC3N9N77UmT_CS#rBvjJYbMCVx "Male"
* item[+].linkId = "F3ogKBuviRA"
* item[=].answer[+].valueString = "[-100.9483,66.6805]"
