// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-VBqh0ynB2wv
InstanceOf: Questionnaire
Title: "Questionnaire - Malaria case registration"
Description: "DHIS2 event program Malaria case registration (VBqh0ynB2wv) as a data capture form."
Usage: #definition
* id = "VBqh0ynB2wv"
* extension[D2FormType].valueCode = #event
* extension[D2DateLabels].extension[eventDate].valueString = "Report date"
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-VBqh0ynB2wv-org-units)
* url = "http://example.org/fhir/examples/patient-summary/Questionnaire/VBqh0ynB2wv"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "VBqh0ynB2wv"
* identifier[+].system = $DHIS2-PROGRAM-CODE
* identifier[=].value = "VBqh0ynB2wv"
* name = "D2PR_VBqh0ynB2wv"
* title = "Malaria case registration"
* description = "DHIS2 event program Malaria case registration (VBqh0ynB2wv) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Location
* code = D2FormType_CS#event
* item[+].linkId = "qrur9Dvnyt5"
* item[=].code = D2DE_CS#qrur9Dvnyt5 "Age in years"
* item[=].text = "Age (years)"
* item[=].type = #integer
* item[=].required = true
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Age of person in years."
* item[=].extension[=].valueString.extension[+].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].extension[=].valueString.extension[=].extension[+].url = "lang"
* item[=].extension[=].valueString.extension[=].extension[=].valueCode = #es
* item[=].extension[=].valueString.extension[=].extension[+].url = "content"
* item[=].extension[=].valueString.extension[=].extension[=].valueString = "Edad en años"
* item[=].extension[=].valueString.extension[+].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].extension[=].valueString.extension[=].extension[+].url = "lang"
* item[=].extension[=].valueString.extension[=].extension[=].valueCode = #fr
* item[=].extension[=].valueString.extension[=].extension[+].url = "content"
* item[=].extension[=].valueString.extension[=].extension[=].valueString = "Âge en années"
* item[+].linkId = "oZg33kd9taw"
* item[=].code = D2DE_CS#oZg33kd9taw "Gender"
* item[=].text = "Gender"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_pC3N9N77UmT_VS)
* item[=].required = true
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Gender of patient."
* item[+].linkId = "F3ogKBuviRA"
* item[=].code = D2DE_CS#F3ogKBuviRA "Household location"
* item[=].text = "Household location"
* item[=].type = #string
